import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/">
          <h1>
            <span>Kajgod blog</span>
          </h1>
        </Link>
        <p className="small">
          2023<span className="highlight">01</span>09
        </p>
        <h2>Next.js app on github pages</h2>
        <p>Čini mi se kako će ovo proć OK.</p>
      </main>

      <footer></footer>
    </>
  );
}
